import type { ProficiencyCode } from "./constants";
import type { TrainingObjective } from "./types";

/**
 * The AFROTCI 36-2011 Vol 1 "Objective Proficiency Code Key" (source document,
 * Objective Proficiency Codes section). This is the generic definition of each
 * code, independent of any specific objective -- reproduced verbatim as the
 * basis for the per-objective "what to look for" criteria below.
 */
export const PROFICIENCY_CODE_DEFINITIONS: Record<ProficiencyCode, { label: string; definition: string; frame: string }> = {
  Ka: {
    label: "Ka — Recall (Bloom's Remember)",
    definition: "Recall basic facts from memory.",
    frame: "Cadet can recall, from memory, each of the following:",
  },
  Kb: {
    label: "Kb — Summarize (Bloom's Understand)",
    definition: "Summarize basic facts from memory and draw conclusions about the subject.",
    frame: "Cadet can summarize from memory and draw conclusions about each of the following:",
  },
  P1: {
    label: "P1 — Partially Proficient (do/participate)",
    definition: "Can do most parts of the task. Needs only help on the hardest parts.",
    frame: "Cadet can do most of the following independently, needing help only on the hardest parts:",
  },
  P2: {
    label: "P2 — Competent (command, direct)",
    definition: "Can do all parts of the task. Needs only a spot check of completed work.",
    frame: "Cadet independently completes all of the following, needing only a spot check of the finished work:",
  },
  P3: {
    label: "P3 — Highly Proficient (coach/mentor, supervise, instruct)",
    definition: "Can do the complete task quickly and accurately. Can tell or show others how to do the task.",
    frame: "Cadet completes all of the following quickly and accurately, and can coach or instruct others through each:",
  },
};

export interface LookForCriteria {
  code: ProficiencyCode;
  label: string;
  frame: string;
  bullets: string[];
}

/** Parses a proficiency-table cell into the code(s) it names -- usually one ("P3"), occasionally a composite ("P1/P2"). */
function parseProficiencyCodes(cell: string): ProficiencyCode[] {
  return cell
    .split("/")
    .map((s) => s.trim())
    .filter((s): s is ProficiencyCode => s in PROFICIENCY_CODE_DEFINITIONS);
}

/**
 * Builds "what should've been observed" criteria for one objective, one per
 * proficiency code that actually applies to it (from its proficiencyByLevel
 * cells) -- generated by combining the generic code definition above with the
 * objective's own Performance Measures, rather than one-off authored text per
 * objective. Required-only bullets are used as the checklist (optional ones
 * are noted but not required for any level).
 */
export function getLookForCriteria(objective: TrainingObjective): LookForCriteria[] {
  const codes = new Set<ProficiencyCode>();
  for (const cell of Object.values(objective.proficiencyByLevel)) {
    for (const code of parseProficiencyCodes(cell)) codes.add(code);
  }

  const requiredBullets = objective.performanceMeasures.filter((pm) => !pm.optional).map((pm) => pm.text);
  const optionalBullets = objective.performanceMeasures.filter((pm) => pm.optional).map((pm) => pm.text);
  const bullets = requiredBullets.length > 0 ? requiredBullets : optionalBullets;

  // Ordinal order Ka < Kb < P1 < P2 < P3, matching the code key's own progression.
  const order: ProficiencyCode[] = ["Ka", "Kb", "P1", "P2", "P3"];
  return order
    .filter((code) => codes.has(code))
    .map((code) => {
      const def = PROFICIENCY_CODE_DEFINITIONS[code];
      return { code, label: def.label, frame: def.frame, bullets };
    });
}
